field: 1e915834-a9e5-4736-aa84-209add6fb4e3 # Socials
fieldLayouts:
  620a7276-c701-459f-b669-a245df921d2a:
    tabs:
      -
        elements:
          -
            fieldUid: eea4a67d-6903-474b-9823-a19906a0e71c # Link
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  eea4a67d-6903-474b-9823-a19906a0e71c: # Link
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialLink
    instructions: ''
    name: Link
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
      types:
        - url
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
handle: website
name: Website
sortOrder: 4
