fieldLayouts:
  41b398ac-15c4-40b0-bcda-d804508925da:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f2e7b889-f463-4dfa-9f10-8da7f7616b47 # Image
            instructions: 'Image should ideally be 2880px wide, compressed JPG'
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1c6366e0-70b7-4921-aea0-2165f1dd55c4 # Video
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9638c31-2f7a-45fd-b771-4cb2146e48b6 # Preview Video
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bfef7c64-5d17-4c0f-b84b-be25ad40257c # Category
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7c550879-ba64-47e7-a95e-f8d01064181d # Client
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc041747-daa7-4cae-bff5-e402655fb752 # Credit
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 44f8bb4e-fd2e-4680-997b-a3b80266a3e3 # Copy
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: projects
hasTitleField: true
name: Projects
section: d9c056ab-bc04-4f7e-b61d-6c7b8ce80732 # Projects
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
