contentColumnType: string
fieldGroup: d5c24e8d-4e91-427e-b900-7a257cb2b034 # General
handle: aspectRatio
instructions: ''
name: 'Aspect Ratio'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - Landscape
        -
          - value
          - landscape
    -
      __assoc__:
        -
          - default
          - '1'
        -
          - label
          - Portrait
        -
          - value
          - portrait
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
