contentColumnType: text
fieldGroup: d5c24e8d-4e91-427e-b900-7a257cb2b034 # General
handle: caption
instructions: ''
name: Caption
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
