contentColumnType: boolean
fieldGroup: 20ad2dfb-5b0d-4ef8-9ccf-dfb17fa54e0f # Projects
handle: playPreview
instructions: ''
name: 'Play Preview'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
