contentColumnType: string(255)
fieldGroup: 20ad2dfb-5b0d-4ef8-9ccf-dfb17fa54e0f # Projects
handle: previewVideo
instructions: 'Direct link to Vimeo File Link, should be full URL, I''d suggest either Standard def (mp4, 960x540) or High def (mp4, 1280x720) depending on how large you are displaying'
name: 'Preview Video'
searchable: true
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
