contentColumnType: text
fieldGroup: babec676-5bc2-4104-9562-f948eed0e575 # SEO
handle: seoDescription
instructions: ''
name: 'SEO Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
