contentColumnType: string
fieldGroup: 20ad2dfb-5b0d-4ef8-9ccf-dfb17fa54e0f # Projects
handle: width
instructions: ''
name: Width
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 1/6
        -
          - value
          - 'small-12 medium-2'
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 1/3
        -
          - value
          - 'small-12 medium-4'
    -
      __assoc__:
        -
          - default
          - '1'
        -
          - label
          - 1/2
        -
          - value
          - 'small-12 medium-6'
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 2/3
        -
          - value
          - 'small-12 medium-8'
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 5/6
        -
          - value
          - 'small-12 medium-10'
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 1/1
        -
          - value
          - 'small-12 medium-12'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
