fieldLayouts:
  37c6ad79-a351-46db-8d48-2d56844da57d:
    tabs:
      -
        elements:
          -
            fieldUid: a4b70625-63de-4771-add9-d3e64edf1f32 # SEO Analytics
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cd29209e-4e1e-4a98-96ef-71615fc8cdc3 # SEO Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 43e9a6c2-179f-4985-9ffa-11fba91af6bb # SEO Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 71176c0d-cdad-4c27-9aee-32771deb70e9 # SEO Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 1
handle: seo
name: SEO
