enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0c3138de-61c9-4e2d-8982-aa68a6127f5f: # Grant Armour
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
